import { useContext } from "react";
import AuthContext from "../../context/AuthContext";

// The useAuth hook is a custom hook that provides access to the authentication context in our components. It uses the useContext hook to consume the AuthContext and return the context value, which includes the login method. By using this custom hook, we can easily access the authentication context in any component that needs it without having to import the AuthContext and use the useContext hook directly in each component. This helps to keep our code clean and organized, and makes it easier to manage the authentication state across our application.
// The useAuth hook is a simple wrapper around the useContext hook that provides a more convenient way to access the authentication context. It abstracts away the details of how the context is implemented and allows us to focus on using the authentication functionality in our components.
// By using the useAuth hook, we can easily access the login method and other authentication-related functionality in any component that needs it, without having to worry about how the context is implemented or how to consume it directly. This makes our code more modular and easier to maintain, as we can change the implementation of the authentication context without having to update all the components that consume it.
// Overall, the useAuth hook is a useful tool for managing authentication state in a React application, and helps to keep our code clean and organized by providing a simple and consistent way to access the authentication context across our components.

// `use` is a convention for naming custom hooks in React. It indicates that the function is a hook and should be used in a React component. By following this convention, we can easily identify custom hooks in our code and understand their purpose. In this case, `useAuth` is a custom hook that provides access to the authentication context, allowing us to manage user authentication state across our application in a clean and organized way. // In this function, we can use react hooks like `useContext` because of `use` prefix used with this react component to consume the `AuthContext` and return the context value, which includes the `login` method. This allows us to easily access the authentication functionality in any component that needs it, without having to worry about how the context is implemented or how to consume it directly. Overall, using the `use` convention for naming custom hooks helps to improve code readability and maintainability in React applications.
export const useAuth = () => {
    const { login, authUser, getLoggedInUser, authLoading } = useContext(AuthContext);  // useContext is a React hook that allows us to consume a context value in a functional component. In this case, we are using the useContext hook to consume the AuthContext and extract the login method from it. By calling useContext(AuthContext), we get access to the value provided by the AuthProvider component, which includes the login method. This allows us to easily access the authentication functionality in any component that needs it, without having to worry about how the context is implemented or how to consume it directly. // { login } is a destructuring assignment that extracts the login method from the context value returned by useContext(AuthContext). This allows us to use the login method directly in our component without having to reference the entire context object. By using destructuring, we can make our code cleaner and more concise, and focus on the specific functionality that we need from the context. 

    return { login, authUser, getLoggedInUser, authLoading };  // we are returning an object that contains the login method, authUser state, and getLoggedInUser method from the authentication context. This allows us to easily access these values in any component that uses the useAuth hook, without having to worry about how the context is implemented or how to consume it directly. By returning these values in an object, we can also easily add more authentication-related functionality to our context in the future without having to change the way we consume it in our components. Overall, this return statement provides a convenient way to access the authentication functionality and state across our application using the useAuth hook.
}