import axios from "axios";
import Cookies from "js-cookie";

const axiosInstance = axios.create({
    baseURL: import.meta.env.VITE_APP_BASE_URL,  // we are using environment variable to set the base URL for the API. this way we can easily change the base URL for different environments (development, staging, production) without changing the code. we can set the environment variable in a .env file at the root of our project and it will be automatically loaded by Vite.
    // ${import.meta.env.VITE_APP_BASE_URL} is a way to access the environment variable VITE_APP_BASE_URL in our code. we can use this variable to set the base URL for our API requests, which allows us to easily switch between different API endpoints for different environments (e.g., development, staging, production) without having to change the code. by using environment variables, we can keep sensitive information (like API keys) out of our codebase and manage configuration more effectively. Where, - import.meta is a special object in JavaScript that provides metadata about the current module. - env is a property of import.meta that contains the environment variables defined in our project. - VITE_APP_BASE_URL is the name of the environment variable that we have defined in our .env file to store the base URL for our API.

    timeout: 50000,  // we are setting a timeout of 50000 milliseconds (50 seconds) for all requests made using this axios instance. this means that if the server does not respond within 50 seconds, the request will be aborted and an error will be thrown. this is useful to prevent our application from hanging indefinitely if the server is not responding or if there are network issues. The default timeout for axios is 0, which means that there is no timeout and the request will wait indefinitely for a response from the server. by setting a timeout, we can ensure that our application remains responsive and does not hang indefinitely in case of server issues or network problems.

    timeoutErrorMessage: "The request took too long and was aborted. Please try again later.",  // we are setting a custom error message for timeout errors. this message will be displayed to the user if the request takes longer than the specified timeout duration (50000 milliseconds in this case) and is aborted. this is useful to provide a better user experience by informing the user about the reason for the error and suggesting them to try again later instead of showing a generic error message or leaving them wondering why the request failed.

    headers: {
        "Content-Type": "application/json",  // we are setting the Content-Type header to application/json for all requests made using this axios instance. this means that we are sending JSON data in the request body.
    },

    // Since With fetch, we must manually JSON.stringify our JS object and set the Content-Type header. Axios does this automatically for plain objects, so we can pass the object directly without calling JSON.stringify.

    responseType: "json",  // we are setting the responseType to json for all requests made using this axios instance. this means that we expect to receive JSON object in the response from the server and even though axios automatically parse the JSON data into a JavaScript object before returning it to us. this is useful to simplify our code and avoid having to manually parse the JSON data from the response every time we make a request to the server. by setting the responseType to json, we can directly work with JavaScript objects in our code instead of dealing with raw JSON strings. We used this for clarity, consistency, handling edge cases and to explicitly specify our expectations for the response format, even though axios would handle this automatically based on the Content-Type header of the response.
});

// Benefits of using an axios instance:
// 1. We can set a base URL for all requests, which makes it easier to manage and update the API endpoint in one place.
// 2. We can set default headers for all requests, which is useful for authentication tokens or content type.
// 3. We can set a timeout for all requests, which helps to prevent our application from hanging indefinitely if the server is not responding.
// 4. We can set a custom error message for timeout errors, which provides a better user experience by informing the user about the reason for the error and suggesting them to try again later.
// 5. We can set the response type for all requests, which simplifies our code by automatically parsing the response data into the desired format (e.g., JSON) before returning it to us.

// Major benefits:
// Interceptors: is a powerful feature of axios that allows us to intercept requests and responses before they are handled by then or catch. This allows us to modify the request or response, add authentication tokens, handle errors globally, etc. For example, we can use an interceptor to automatically add an authentication token to the headers of every request, or to log the details of every response for debugging purposes. Interceptors can be added to the axios instance using the interceptors property, which provides methods for adding request and response interceptors. This feature is particularly useful for managing API interactions in a consistent way across our application and for handling common tasks such as authentication and error handling in a centralized manner.
// Intercepting requests and responses: We can use axios interceptors to intercept requests and responses before they are handled by then or catch. This allows us to modify the request or response, add authentication tokens, handle errors globally, etc.
// Canceling requests: We can use axios cancel tokens to cancel requests if they are no longer needed, which can help to improve performance and reduce unnecessary network traffic.
// Creating multiple instances: We can create multiple axios instances with different configurations (e.g., different base URLs, headers, timeouts) for different parts of our application, which allows us to manage API interactions more effectively and maintain cleaner code.


// How LoginForm.tsx component will interact with the API using this axios instance:
/*
```
React Component => Service(axios -> intercept) => Internet => Dummyjson API (or any other API) => Internet => Axios Instance(intercept -> response) => React Component
 ```

- In this flow, the React component (e.g., LoginForm) will call a service function that uses the axios instance to make an API request to the server (e.g., to authenticate the user). The axios instance will handle the request and response, including any interceptors that we have set up for adding authentication tokens or handling errors. The response from the server will be returned to the React component, which can then update the UI based on the response (e.g., show a success message, redirect the user, display error messages, etc.). This flow allows us to manage API interactions in a consistent way across our application and to handle common tasks such as authentication and error handling in a centralized manner using the axios instance and its features.
*/

// There are two types of API:
// i) Public API: which can be accessed without authentication (e.g., fetching product data, fetching user profiles, etc.)
// ii) Private API: which requires authentication (e.g., creating a new user, updating user information, etc.). For private APIs, we need to include an authentication token (e.g., JWT) in the headers of the request to access the protected resources on the server. We can use axios interceptors to automatically add the authentication token to the headers of every request that requires authentication, which simplifies our code and ensures that we are consistently including the necessary authentication information in our API requests. 


// request interceptor:
// axiosInstance.interceptors.request.use( callbackFunction, errorFunction )

axiosInstance.interceptors.request.use((config) => {   // config is the request configuration object that will be passed to the callback function. this object contains all the details of the request that is about to be sent to the server, such as the URL, method, headers, data, etc. we can modify this configuration object in the callback function before it is sent to the server.  // this is the callback function that will be called with the request configuration object before the request is sent. we can modify the request configuration (e.g., by adding headers) and then return the modified configuration object, which will be used for the actual request. for example, we can add an authentication token to the headers of every request like this:
    console.log("I'm in the request interceptor");  // we are logging a message to the console to indicate that we are in the request interceptor. this can be helpful for debugging purposes to confirm that the interceptor is being executed before the request is sent to the server.
    console.log("Request Interceptor: ", config);  // we are logging the request configuration object to the console for debugging purposes. this allows us to see the details of the request that is about to be sent to the server, which can be helpful for troubleshooting issues with our API requests and ensuring that the request is being configured correctly before it is sent.

    const token = Cookies.get("auth_key");  // we are getting the authentication token from cookies storage. this assumes that we have previously stored the token in cookies storage after a successful login. we can replace "auth_key" with the actual key that we used to store the token in cookies storage.
    if (token) {
        config.headers.Authorization = `Bearer ${token}`;   // if the token exists, we are adding it to the Authorization header of the request. we are using the Bearer authentication scheme, which is a common way to include JWT tokens in the headers of API requests. this means that the server will expect the token to be included in the Authorization header and will use it to authenticate the request and determine if the user has access to the requested resource. by adding the token to the headers of every request, we can ensure that our application is consistently including the necessary authentication information when making API requests to private endpoints on the server.
    }
    return config;

});  // we can use this method to add a request interceptor to our axios instance. this allows us to intercept requests before they are sent to the server and modify them as needed (e.g., adding authentication tokens, logging request details, etc.). we can pass a function as an argument to this method that will be called with the request configuration object before the request is sent. this function can modify the request configuration (e.g., by adding headers) and then return the modified configuration object, which will be used for the actual request. // axiosInstance is the instance of axios that we created with our custom configuration (base URL, timeout, headers, response type). // `.interceptors` is a property of the axios instance that allows us to add interceptors for requests and responses. // `.request` is a method of the interceptors property that allows us to add a request interceptor. // `.use` is a method of the request interceptors that allows us to specify a function that will be called with the request configuration object before the request is sent. // This function can modify the request configuration (e.g., by adding authentication tokens to the headers) and then return the modified configuration object, which will be used for the actual request. // This is useful for handling common tasks such as adding authentication tokens to every request, logging request details for debugging purposes, or modifying the request in other ways before it is sent to the server.



// response interceptor:
// axiosInstance.interceptors.response.use( callbackFunction, errorFunction )
// In response interceptors, there are two modes: success and error. the callback function will be called with the response object if the response is successful (e.g., status code 200), and the error function will be called with the error object if the response is an error (e.g., status code 400 or 500). we can use these interceptors to handle responses globally, such as logging response details, handling specific error codes, etc. for example, we can check for specific error codes in the response and handle them globally (e.g., if we receive a 401 Unauthorized error, we can automatically log the user out and redirect them to the login page). this allows us to manage API responses in a consistent way across our application and to handle common tasks such as error handling in a centralized manner using the axios instance and its features.

//---
// axiosInstance.interceptors.response.use(
// if success => response.data => value => is Server's actual response  // and, response(object) => is the response object that axios wraps around the actual response from the server, which contains additional information about the response (e.g., status code, headers, etc.) and the actual response data from the server is contained in the data property of the response object. by returning response.data in the success callback of the response interceptor, we can simplify our code and directly work with the actual data that we are interested in from the response, rather than having to access it through the response object every time we handle a response in our code. this allows us to write cleaner and more concise code when working with API responses in our application. for example, if we receive a successful response from the server with a JSON object containing user information, we can directly access that user information as a JavaScript object in our code without having to navigate through the response object to get to it.

// if error (except 5xx) => error.response.data => {...response} => is Server's actual response in case of error
// if response status value is out of the range of 5xx and it is error response, then the servers actual response is in error.response property of the error object. this is because axios treats responses with status codes outside the range of 2xx as errors and will reject the promise with an error object that contains the actual response from the server in the error.response property. this allows us to access the details of the error response (e.g., status code, headers, data) and handle it accordingly in our code. for example, we can check for specific error codes in the error.response and handle them globally (e.g., if we receive a 401 Unauthorized error, we can automatically log the user out and redirect them to the login page). this is useful for managing API responses in a consistent way across our application and for handling common tasks such as error handling in a centralized manner using the axios instance and its features.
//)
//---
axiosInstance.interceptors.response.use(
    (response) => {
        // this is the callback function that will be called with the response object if the response is successful (e.g., status code 200). we can modify the response (e.g., by checking for specific error codes) and then return the modified response object, which will be used for the actual response handling in our code. for example, we can check for specific error codes in the response and handle them globally (e.g., if we receive a 401 Unauthorized error, we can automatically log the user out and redirect them to the login page).
        console.log("I'm in the success response interceptor");  // we are logging a message to the console to indicate that we are in the response interceptor. this can be helpful for debugging purposes to confirm that the interceptor is being executed before the response is handled by then or catch.
        console.log("Response Interceptor: ", response);  // we are logging the response object to the console for debugging purposes. this allows us to see the details of the response that is being received from the server, which can be helpful for troubleshooting issues with our API responses and ensuring that the response is being handled correctly before it is processed by then or catch.

        return response.data;  // we are returning the data property of the response object. this is because axios automatically wraps the response data in a response object that contains additional information about the response (e.g., status code, headers, etc.). by returning response.data, we can simplify our code and directly work with the actual data that we are interested in from the response, rather than having to access it through the response object every time we handle a response in our code.
    },
    (error) => {
        // this is the error function that will be called with the error object if the response is an error (e.g., status code 400 or 500). we can modify the error (e.g., by checking for specific error codes) and then return the modified error object, which will be used for the actual error handling in our code. for example, we can check for specific error codes in the error and handle them globally (e.g., if we receive a 401 Unauthorized error, we can automatically log the user out and redirect them to the login page).
        console.log("I'm in the error response interceptor");  // we are logging a message to the console to indicate that we are in the response interceptor. this can be helpful for debugging purposes to confirm that the interceptor is being executed before the response is handled by then or catch.
        // console.log("Response Interceptor Error: ", error);  // we are logging the error object to the console for debugging purposes. this allows us to see the details of the error that is being received from the server, which can be helpful for troubleshooting issues with our API responses and ensuring that the error is being handled correctly before it is processed by then or catch.
        // console.error("Response Interceptor Error: ", error);  // we are logging the error object to the console as an error for better visibility in the console. this allows us to easily identify and troubleshoot issues with our API responses by clearly indicating that an error has occurred in the response interceptor.
        // console.error("Response Interceptor Error: ", error.response.data);  // we are logging the error response object to the console as an error for better visibility in the console. this allows us to easily identify and troubleshoot issues with our API responses by clearly indicating that an error has occurred in the response interceptor and providing details about the error response from the server (e.g., status code, headers, data) for further analysis.
        if (error.status === 400 || error.status === 422) {
            // validation error
            throw error?.response?.data;  // we are throwing the error response data from the server if the error status code is 400 (Bad Request) or 422 (Unprocessable Entity), which are commonly used for validation errors. this allows us to handle validation errors in a consistent way across our application and to provide specific feedback to the user about what went wrong with their request (e.g., which fields were invalid, what the validation rules are, etc.). by throwing the error response data, we can catch it in our components and display appropriate error messages to the user based on the details provided in the error response from the server.
        } else {
            throw error?.response;  // for other types of errors (e.g., server errors, network errors, etc.), we are throwing the entire error response object from the server. this allows us to handle these types of errors in a consistent way across our application and to provide specific feedback to the user about what went wrong with their request (e.g., if there was a server error, we can display a generic error message to the user). by throwing the error response object, we can catch it in our components and display appropriate error messages to the user based on the details provided in the error response from the server.
        }

        // return Promise.reject(error);  // we are rejecting the promise with the error object. this allows us to handle errors in a consistent way across our application and to propagate errors up the call stack so that they can be handled by appropriate error boundaries or catch blocks. by rejecting the promise with the error object, we can catch it in our components and display appropriate error messages to the user based on the details provided in the error response from the server. this is useful for managing API responses in a consistent way across our application and for handling common tasks such as error handling in a centralized manner using the axios instance and its features.
    }
);  // we can use this method to add a response interceptor to our axios instance. this allows us to intercept responses before they are handled by react component and, `then` or, `catch` and modify them as needed (e.g., handling errors globally, logging response details, etc.). we can pass a function as an argument to this method that will be called with the response object before it is handled by react component and, `then` or, `catch`. this function can modify the response (e.g., by checking for specific error codes) and then return the modified response object, which will be used for the actual response handling in our code. 



export default axiosInstance;  // we are exporting the axios instance so that we can use it in other parts of our application to make API requests. by using this axios instance, we can ensure that all our API requests have a consistent configuration (base URL, timeout, headers, response type) and we can easily manage and update this configuration in one place if needed. we can import this axios instance in any file where we need to make API requests and use it to send requests to the server and handle responses in a consistent way across our application.
